trigger:
 branches:
  include:
   - main
 paths:
  include:
  - '01-BasicPipeline/*'

pool:
 vmimage: 'ubuntu-latest'

steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          
          echo 'Hello world'